// statics/src/App.jsx
import React, { Component } from 'react';

class App extends Component {
  render() {
    return <div>
         <div className="navbar navbar-inverse navbar-static-top">
            <div className="container">
                <div className="navbar-header">
                    <button type="button" className="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span className="icon-bar"></span>
                        <span className="icon-bar"></span>
                        <span className="icon-bar"></span>
                    </button>
                    <a href="/" className="navbar-brand">Podcasts</a>
                </div>
                <div className="navbar-collapse collapse">
                    <ul className="nav navbar-nav">
                        <li className="active"><a href="#">Home</a></li>
                        <li><a href="#about">About</a></li>
                        <li><a href="#contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div className="container body-content">
            <div>
                {this.props.children}
            </div>
            <hr />
            <footer>
                <p>&copy; 2016 - My ASP.NET Application</p>
            </footer>
        </div>
    </div>
  }
}

export default App;

// statics/src/app/app.component.ts
import { Component } from '@angular/core';
import { PodcastListComponent } from './podcasts/podcast-list.component';

@Component({
  selector: 'pod-app',
  templateUrl: './app.component.html',
})
export class AppComponent { }
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false"
        aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
      <a class="navbar-brand" routerLink="/podcasts">Adhoc Podcasts</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li [routerLinkActive]="['active']" [routerLinkActiveOptions]="{exact:true}"><a href="#" routerLink="/podcasts">Podcasts</a></li>
        <li [routerLinkActive]="['active']" [routerLinkActiveOptions]="{exact:true}"><a href="#" routerLink="/podcasts/new">Create</a></li>
      </ul>
    </div>
    <!--/.nav-collapse -->
  </div>
</nav>

<div class="container nav-bar-space">
  <router-outlet></router-outlet>
</div>
